### ISSUE TITLE
Get string with formatted object

### ISSUE THREAD

**Issue by Alonely0** [aDotInTheVoid/debug2#4]
I have my own macros for printing stuff on different situations and not putting conditionals everywhere, for example:
```rs
macro_rules! println_on_debug {
    ($($args:tt)*) => {
        if std::env::var("DEBUG").unwrap_or_else(|_| { "false".to_string() }) == "true" ||
           env!("CARGO_PKG_VERSION").ends_with("dev") {
               println!("DEBUG-MSG: {}", format!{ $($args)* })
        }
    };
}
```
I'd like to make that macro print objects with the same formatting as pprint, the problem is that pprint is not a macro that sends args to a formatter and redirects the output to stdout, pprint is a function that just formats & prints a complex structure. My suggestion consists in creating a function that instead of printing the formatted structure to stdout, just returns it, so I can call that macro like this:
```rs
println_on_debug!("struct: {}", pformat(complex_structure));
```

**Comment by aDotInTheVoid** [comment]
`pprint` literaly does this. It returns a string. https://docs.rs/debug2/0.1.0/debug2/fn.pprint.html

I guess the name is confusing.

Closing, but feel free to reopen if I misunderstood
